version: 2

sources:
  - name: Staging
    database: nyc_taxi_trip
    schema: public

    tables:
      - name: green_trip
      - name: yellow_trip
      - name: zone_lookup

models:
  - name: green_trip
    description: >
      Trip data for green taxis.
    columns:
      - name: VendorID 
        description: > 
          A code indicating the TPEP provider that provided the record.
          1 = Creative Mobile Technologies, LLC; 
          2 = VeriFone Inc.
      - name: lpep_pickup_datetime 
        description: >
          The time and date when the trip started.
      - name: lpep_dropoff_datetime
        description: >
          The time and date when the trip ended.
      - name: store_and_fwd_flag 
        description: >
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor.
          Y = store and forward trip,
          N = not a store and forward trip.
      - name: RatecodeID
        description: >
          The final rate code in effect at the end of the trip.
          1 = Standard rate,
          2 = JFK,
          3 = Newark,
          4 = Nassau or Westchester,
          5 = Negotiated fare,
          6 = Group ride.
      - name: PULocationID
        description: >
          The location ID where the trip started.
        tests: 
          - relationships:
              to: ref('zone_lookup')
              field: LocationID
      - name: DOLocationID
        description: >
          The location ID where the trip ended.
        tests: 
          - relationships:
              to: ref('zone_lookup')
              field: LocationID
      - name: passenger_count
        description: >
          The number of passengers in the trip, entered by the driver.
      - name: trip_distance
        description: >
          The trip distance in miles, reported by the taximeter.
      - name: fare_amount
        description: >
          The time-and-distance fare calculated by the meter.
      - name: extra
        description: >
          Miscellaneous extras like tolls, airport fees, etc.
      - name: mta_tax
        description: >
          Tax amount collected by the NYC MTA.
      - name: tip_amount
        description: >
          Tip amount paid to the driver, if any.
      - name: tolls_amount
        description: >
          Total amount of tolls paid during the trip.
      - name: improvement_surcharge
        description: >
          A $0.30 surcharge meant to improve the overall NYC taxi system.
      - name: total_amount
        description: >
          The total amount charged for the trip, including all extras and taxes.
      - name: payment_type
        description: >
          A code explaining how the passenger paid.
          1 = Credit card,
          2 = Cash,
          3 = No charge,
          4 = Dispute,
          5 = Unknown.
      - name: trip_type
        description: >
          A code indicating whether the trip was dispatched from a garage or hailed by a passenger on the street.
          1 = Street-hail,
          2 = Dispatch.
      - name: congestion_surcharge
        description: >
          A $2.50 surcharge for trips that begin or end in Manhattan below 96th Street.

  - name: yellow_trip
    description: >
      Trip data for yellow taxis.
    columns:
      - name: VendorID 
        description: > 
          A code indicating the TPEP provider that provided the record.
          1 = Creative Mobile Technologies, LLC; 
          2 = VeriFone Inc.
      - name: tpep_pickup_datetime 
        description: >
          The time and date when the trip started.
      - name: tpep_dropoff_datetime
        description: >
          The time and date when the trip ended.
      - name: store_and_fwd_flag 
        description: >
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor.
          Y = store and forward trip,
          N = not a store and forward trip.
      - name: RatecodeID
        description: >
          The final rate code in effect at the end of the trip.
          1 = Standard rate,
          2 = JFK,
          3 = Newark,
          4 = Nassau or Westchester,
          5 = Negotiated fare,
          6 = Group ride.
      - name: PULocationID
        description: >
          The location ID where the trip started.
        tests: 
          - relationships:
              to: ref('zone_lookup')
              field: LocationID
      - name: DOLocationID
        description: >
          The location ID where the trip ended.
        tests: 
          - relationships:
              to: ref('zone_lookup')
              field: LocationID
      - name: passenger_count
        description: >
          The number of passengers in the trip, entered by the driver.
      - name: trip_distance
        description: >
          The trip distance in miles, reported by the taximeter.
      - name: fare_amount
        description: >
          The time-and-distance fare calculated by the meter.
      - name: extra
        description: >
          Miscellaneous extras like tolls, airport fees, etc.
      - name: mta_tax
        description: >
          Tax amount collected by the NYC MTA.
      - name: tip_amount
        description: >
          Tip amount paid to the driver, if any.
      - name: tolls_amount
        description: >
          Total amount of tolls paid during the trip.
      - name: improvement_surcharge
        description: >
          A $0.30 surcharge meant to improve the overall NYC taxi system.
      - name: total_amount
        description: >
          The total amount charged for the trip, including all extras and taxes.
      - name: payment_type
        description: >
          A code explaining how the passenger paid.
          1 = Credit card,
          2 = Cash,
          3 = No charge,
          4 = Dispute,
          5 = Unknown.
      - name: trip_type
        description: >
          A code indicating whether the trip was dispatched from a garage or hailed by a passenger on the street.
          1 = Street-hail,
          2 = Dispatch.
      - name: congestion_surcharge
        description: >
          A $2.50 surcharge for trips that begin or end in Manhattan below 96th Street.

  - name: zone_lookup
    description: >
      A lookup table containing the taxi zone information for NYC trips.
    columns:
      - name: LocationID
        description: >
          Unique identifier for each taxi zone.
        tests: 
          - unique
          - not_null
      - name: Borough
        description: >
          The borough where the taxi zone is located 
      - name: Zone
        description: >
          The specific name of the taxi zone 
      - name: service_zone
        description: >
          The service zone classification 
